/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB2;

/**
 *
 * @author nguye
 */
public class bai2 extends javax.swing.JFrame {

    /**
     * Creates new form bai2
     */
    public bai2() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtResult = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSo1 = new javax.swing.JButton();
        btnSo2 = new javax.swing.JButton();
        btnSo3 = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();
        btnSQRT = new javax.swing.JButton();
        btnSo4 = new javax.swing.JButton();
        btnSo5 = new javax.swing.JButton();
        btnSo6 = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnPhanTram = new javax.swing.JButton();
        btnSo7 = new javax.swing.JButton();
        btnSo8 = new javax.swing.JButton();
        btnSo9 = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnMotPhanX = new javax.swing.JButton();
        btnSo0 = new javax.swing.JButton();
        btnCongVaTru = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCong = new javax.swing.JButton();
        btnBang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CASIO");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtResult.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtResult.setForeground(new java.awt.Color(0, 0, 255));
        txtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResult.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResult)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.GridLayout(4, 5, 5, 5));

        btnSo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSo1.setText("1");
        btnSo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSo1);

        btnSo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSo2.setText("2");
        btnSo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSo2);

        btnSo3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSo3.setText("3");
        btnSo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSo3);

        btnChia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChia.setText("/");
        btnChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaActionPerformed(evt);
            }
        });
        jPanel3.add(btnChia);

        btnSQRT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSQRT.setText("sqrt");
        btnSQRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSQRTActionPerformed(evt);
            }
        });
        jPanel3.add(btnSQRT);

        btnSo4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSo4.setText("4");
        btnSo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo4ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSo4);

        btnSo5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSo5.setText("5");
        btnSo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo5ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSo5);

        btnSo6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSo6.setText("6");
        btnSo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo6ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSo6);

        btnNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhan.setText("*");
        btnNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanActionPerformed(evt);
            }
        });
        jPanel3.add(btnNhan);

        btnPhanTram.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPhanTram.setText("%");
        btnPhanTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSQRTActionPerformed(evt);
            }
        });
        jPanel3.add(btnPhanTram);

        btnSo7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSo7.setText("7");
        btnSo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo7ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSo7);

        btnSo8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSo8.setText("8");
        btnSo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo8ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSo8);

        btnSo9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSo9.setText("9");
        btnSo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo9ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSo9);

        btnTru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTru.setText("-");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });
        jPanel3.add(btnTru);

        btnMotPhanX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMotPhanX.setText("1/x");
        btnMotPhanX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSQRTActionPerformed(evt);
            }
        });
        jPanel3.add(btnMotPhanX);

        btnSo0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSo0.setText("0");
        btnSo0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo0ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSo0);

        btnCongVaTru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCongVaTru.setText("+/-");
        btnCongVaTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongVaTruActionPerformed(evt);
            }
        });
        jPanel3.add(btnCongVaTru);

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear);

        btnCong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCong.setText("+");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });
        jPanel3.add(btnCong);

        btnBang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBang.setText("=");
        btnBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangActionPerformed(evt);
            }
        });
        jPanel3.add(btnBang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangActionPerformed
        long kq = 0;
        long b = Long.parseLong(txtResult.getText());
            if(pheptoan.length()>0){
                if(pheptoan.equals("+")){
                   kq = a+b;
                   txtResult.setText(String.valueOf(kq));
                }
                else if(pheptoan.equals("-")){
                   kq = a-b;
                   txtResult.setText(String.valueOf(kq));
                }
                else if(pheptoan.equals("*")){
                   kq = a*b;
                   txtResult.setText(String.valueOf(kq));
                }
                if(pheptoan.equals("/")){
                   kq = a/b;
                   txtResult.setText(String.valueOf(kq));
                }
                pheptoan = "";
                a=0;
            }
    }//GEN-LAST:event_btnBangActionPerformed
    private void btnSo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo3ActionPerformed
 String gt = txtResult.getText();
        if(gt.length()<12){
           if(gt.equals(0))
           gt="";
           long so = Long.parseLong(gt + btnSo3.getText());
           txtResult.setText(String.valueOf(so));
           
        }
    }//GEN-LAST:event_btnSo3ActionPerformed

    private void btnSo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo5ActionPerformed
         String gt = txtResult.getText();
        if(gt.length()<12){
           if(gt.equals(0))
           gt="";
           long so = Long.parseLong(gt + btnSo5.getText());
           txtResult.setText(String.valueOf(so));
           
        }
    }//GEN-LAST:event_btnSo5ActionPerformed

    private void btnSo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo2ActionPerformed
        String gt = txtResult.getText();
        if(gt.length()<12){
           if(gt.equals(0))
           gt="";
           long so = Long.parseLong(gt + btnSo2.getText());
           txtResult.setText(String.valueOf(so));
           
        }
    }//GEN-LAST:event_btnSo2ActionPerformed

    private void btnSo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo1ActionPerformed
        // TODO add your handling code here:
         String gt = txtResult.getText();
        if(gt.length()<12){
           if(gt.equals(0))
           gt="";
           long so = Long.parseLong(gt + btnSo1.getText());
           txtResult.setText(String.valueOf(so));
           
        }
    }//GEN-LAST:event_btnSo1ActionPerformed

    private void btnSo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo4ActionPerformed
        // TODO add your handling code here:
         String gt = txtResult.getText();
        if(gt.length()<12){
           if(gt.equals(0))
           gt="";
           long so = Long.parseLong(gt + btnSo4.getText());
           txtResult.setText(String.valueOf(so));
           
        }
    }//GEN-LAST:event_btnSo4ActionPerformed

    private void btnSo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo6ActionPerformed
 String gt = txtResult.getText();
        if(gt.length()<12){
           if(gt.equals(0))
           gt="";
           long so = Long.parseLong(gt + btnSo6.getText());
           txtResult.setText(String.valueOf(so));
           
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSo6ActionPerformed

    private void btnSo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo7ActionPerformed
 String gt = txtResult.getText();
        if(gt.length()<12){
           if(gt.equals(0))
           gt="";
           long so = Long.parseLong(gt + btnSo7.getText());
           txtResult.setText(String.valueOf(so));
           
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSo7ActionPerformed

    private void btnSo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo8ActionPerformed
 String gt = txtResult.getText();
        if(gt.length()<12){
           if(gt.equals(0))
           gt="";
           long so = Long.parseLong(gt + btnSo8.getText());
           txtResult.setText(String.valueOf(so));
           
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSo8ActionPerformed

    private void btnSo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo9ActionPerformed
      String gt = txtResult.getText();
        if(gt.length()<12){
           if(gt.equals(0))
           gt="";
           long so = Long.parseLong(gt + btnSo9.getText());
           txtResult.setText(String.valueOf(so));
           
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnSo9ActionPerformed

    private void btnSo0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo0ActionPerformed
      String gt = txtResult.getText();
        if(gt.length()<12){
           if(gt.equals(0))
           gt="";
           long so = Long.parseLong(gt + btnSo0.getText());
           txtResult.setText(String.valueOf(so));
           
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnSo0ActionPerformed

    private void btnCongVaTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongVaTruActionPerformed
        try {
            double value = Double.parseDouble(txtResult.getText());
            value = -value;
            txtResult.setText(""+value);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCongVaTruActionPerformed

    private void btnChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaActionPerformed
        // TODO add your handling code here:
        a = Long.parseLong(txtResult.getText());
        if(a!=0){
          pheptoan="/";
          txtResult.setText("0");
        }
    }//GEN-LAST:event_btnChiaActionPerformed

    private void btnNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanActionPerformed
        a = Long.parseLong(txtResult.getText());
        if(a!=0){
          pheptoan="*";
          txtResult.setText("0");
        }       
    }//GEN-LAST:event_btnNhanActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        a = Long.parseLong(txtResult.getText());
        if(a!=0){
          pheptoan="-";
          txtResult.setText("0");
        }
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        a = Long.parseLong(txtResult.getText());
        if(a!=0){
          pheptoan="+";
          txtResult.setText("0");
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtResult.setText("0");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSQRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSQRTActionPerformed
        if (txtResult.getText().equals("")){
        return ;
        }
        String gt = evt.getActionCommand();
        try {
            double value = Double.parseDouble(txtResult.getText());
            
                if(gt.equals("sqrt")){
                   value = Math.sqrt(value);
                }else if(gt.equals("%")){
                   value = value / 100;
                }if(gt.equals("1/x")){
                   value = 1/value;
                }
                txtResult.setText(""+value);
        } catch (Exception e) {
           e.printStackTrace();
        }
    }//GEN-LAST:event_btnSQRTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai2().setVisible(true);
            }
        });
    }
    private long a=0;
    private String pheptoan="";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBang;
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnCongVaTru;
    private javax.swing.JButton btnMotPhanX;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnPhanTram;
    private javax.swing.JButton btnSQRT;
    private javax.swing.JButton btnSo0;
    private javax.swing.JButton btnSo1;
    private javax.swing.JButton btnSo2;
    private javax.swing.JButton btnSo3;
    private javax.swing.JButton btnSo4;
    private javax.swing.JButton btnSo5;
    private javax.swing.JButton btnSo6;
    private javax.swing.JButton btnSo7;
    private javax.swing.JButton btnSo8;
    private javax.swing.JButton btnSo9;
    private javax.swing.JButton btnTru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
